# Generated by Django 4.1.5 on 2023-01-18 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Publication Date"
                    ),
                ),
                ("comment", models.TextField(max_length=1024)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (10, "10"),
                            (9, "9"),
                            (8, "8"),
                            (7, "7"),
                            (6, "6"),
                            (5, "5"),
                            (4, "4"),
                            (3, "3"),
                            (2, "2"),
                            (1, "1"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Review",
                "verbose_name_plural": "Book Reviews",
                "ordering": ["-pub_date"],
            },
        ),
    ]
